### PR TITLE
Download Gradle libraries during build

### PR DESCRIPTION
**Pull request by mizdebsk**
XMvn depends on Gradle, which is not published to Maven Central. Previously it was solved by manually publishing missing JARs to a repo on fedorapeople.org or people.redhat.com. This PR is an attempt to get rid of auxiliary repo by downloading Gradle binary distribution and extracting required JARs from there, during XMvn build.

### CODE REVIEW

**Comment by mizdebsk** [comment]
@msimacek @msrb I'm looking for feedback about this change. I'm circumventing standard Maven practices so I'm not sure if it's a "good thing" to do and whether there is a better solution.

**Comment by msimacek** [comment]
Looks ok to me, it's certainly better than the previous state. Could the profile be actiavated by default?

**Comment by msimacek** [comment]
BTW, does gradle upstream have any strong reason why not to release to Maven Central?

**Comment by mizdebsk** [comment]
> Could the profile be actiavated by default?

It could be, but then:
- during standard development cycle `mvn clean verify` Gradle zip would be re-downloaded with each run,
- when importing to IDEs (like Eclipse M2E) you'd get a bunch of useless modules with unsupported plugins.

> BTW, does gradle upstream have any strong reason why not to release to Maven Central?

They don't publish internal JARs to any repos because they don't want them to be used - these JARs don't have any API stability guarantees. (I **could** theoretically deploy them to Central myself, but I figured out I better don't.)

**Pull request merged**
