### PR TITLE
Do not consider optional dependencies to be runtime dependencies

### PR DESCRIPTION
**Pull request by msrb**
As we discussed previously via other channels, it looks like the Maven bug which forced us to treat optional dependencies as runtime dependencies is fixed now. This PR is an attempt to modify XMvn accordingly.

### CODE REVIEW

**Comment by mizdebsk** [comment]
I don't like the approach of ignoring optional dependencies. Remember that metadata is used for other things besides auto-requires generation and all dependencies are needed for other cases. I think that we should include all dependencies in generated metadata and let dependency generator skip generating auto-requires on them.

**Comment by msrb** [comment]
Hmm, I didn't think of that. AFAIK metadata files currently don't carry information whether some particular dependency is optional or not. This will need to be addressed.
Can you think of any particular scenario which could be affected by not including optional dependencies in metadata?

**Comment by mizdebsk** [comment]
XMvn uses metadata to generate effective POM. If you don't include optional dependencies in metadata then generated effective POM will not contain them either, which would affect Maven builds. We can add a new element to metadata specifying whether given dependency is optional or not.

**Comment by msrb** [comment]
Fair enough, I will try to implement it.

**Comment by msrb** [comment]
This functionality is already implemented in XMvn, closing this PR.

**Pull request closed without merging**
